import './core/gameTimer.test';
import './enemy/enemyMovement.test';
import './core/resources.test';
import './core/stats.test';
import './core/eventBus.test';
import './core/integration.test';
import './catalogs/runItemCatalog.test';
import './catalogs/weaponCatalog.test';
import './catalogs/equipmentCatalog.test';
import './catalogs/equipmentProgression.test';
import './catalogs/equipmentLootChoices.test';
import './catalogs/enemyCatalog.test';
import './flows/settlementLootEntry.test';
import './flows/battleFlow.test';
import './flows/hostContextContract.test';
import './ui/revivePanelWiring.test';
import './visual/poisonSprayVfx.test';
import './visual/weaponAttackPresentation.test';
import './state/combatState.test';
import './balance/combatBalance.test';

console.log('All tests passed.');
