import type { EnemySpec } from '../core/types';

export const BASE_ENEMY_ARCHETYPES: EnemySpec[] = [
    {
        id: 'mite',
        name: '碎壳虫',
        family: 'mite',
        artId: 'mite',
        hp: 18,
        speed: 126,
        damage: 4,
        radius: 13,
        xp: 2,
        alloyChance: 0.05,
        color: '#9BE564',
        accent: '#31572C',
        spawnAfter: 0,
        weight: 7,
    },
    {
        id: 'runner',
        name: '疾行体',
        family: 'runner',
        artId: 'runner',
        hp: 24,
        speed: 196,
        damage: 6,
        radius: 12,
        xp: 3,
        alloyChance: 0.08,
        color: '#4CC9F0',
        accent: '#1B4965',
        spawnAfter: 10,
        weight: 4,
    },
    {
        id: 'brute',
        name: '重甲块',
        family: 'brute',
        artId: 'brute',
        hp: 88,
        speed: 78,
        damage: 10,
        radius: 22,
        xp: 8,
        alloyChance: 0.22,
        color: '#F9C74F',
        accent: '#8A5A00',
        spawnAfter: 18,
        weight: 3,
    },
    {
        id: 'splitter',
        name: '裂变囊',
        family: 'splitter',
        artId: 'splitter',
        hp: 54,
        speed: 112,
        damage: 7,
        radius: 18,
        xp: 6,
        alloyChance: 0.16,
        color: '#F15BB5',
        accent: '#6A0572',
        spawnAfter: 28,
        weight: 3,
    },
    {
        id: 'warden',
        name: '磁暴卫士',
        family: 'warden',
        artId: 'warden',
        hp: 160,
        speed: 92,
        damage: 15,
        radius: 26,
        xp: 13,
        alloyChance: 0.35,
        color: '#F3722C',
        accent: '#6B240C',
        spawnAfter: 46,
        weight: 2,
    },
    {
        id: 'bomber',
        name: '自爆虫',
        family: 'bomber',
        artId: 'bomber',
        hp: 14,
        speed: 140,
        damage: 8,
        radius: 14,
        xp: 3,
        alloyChance: 0.05,
        color: '#EF4444',
        accent: '#FCA5A5',
        spawnAfter: 2,
        weight: 3,
    },
    {
        id: 'swarm',
        name: '蜂群',
        family: 'swarm',
        artId: 'swarm',
        hp: 8,
        speed: 140,
        damage: 2,
        radius: 4,
        xp: 1,
        alloyChance: 0.02,
        color: '#EAB308',
        accent: '#FDE047',
        spawnAfter: 5,
        weight: 3,
    },
    {
        id: 'aura',
        name: '灵能体',
        family: 'aura',
        artId: 'aura',
        hp: 40,
        speed: 80,
        damage: 5,
        radius: 16,
        xp: 8,
        alloyChance: 0.12,
        color: '#38BDF8',
        accent: '#BAE6FD',
        spawnAfter: 12,
        weight: 1.5,
    },
    {
        id: 'seeker',
        name: '追踪眼',
        family: 'seeker',
        artId: 'seeker',
        hp: 30,
        speed: 100,
        damage: 8,
        radius: 15,
        xp: 7,
        alloyChance: 0.10,
        color: '#BE123C',
        accent: '#FDA4AF',
        spawnAfter: 10,
        weight: 2,
    },
    {
        id: 'beacon',
        name: '信标',
        family: 'beacon',
        artId: 'beacon',
        hp: 60,
        speed: 0,
        damage: 0,
        radius: 24,
        xp: 12,
        alloyChance: 0.25,
        color: '#CA8A04',
        accent: '#FCD34D',
        spawnAfter: 20,
        weight: 1,
    },
];

// ── 小 Boss（无尽穿插，不挡进度）──────────────────────────────
export const MINI_BOSS_SPECS: EnemySpec[] = [
    // 狂暴重甲块：HP极高、移动慢、接触伤害高
    {
        id: 'brute-prime',
        name: '狂暴重甲块',
        family: 'brute-prime',
        artId: 'brute',
        hp: 600,
        speed: 45,
        damage: 35,
        radius: 30,
        xp: 50,
        alloyChance: 1.0,
        color: '#78350F',
        accent: '#F59E0B',
        spawnAfter: 11,
        weight: 0,
    },
    // 电弧灵能体：短距离连锁闪电
    {
        id: 'aura-arc',
        name: '电弧灵能体',
        family: 'aura-arc',
        artId: 'aura',
        hp: 380,
        speed: 55,
        damage: 22,
        radius: 24,
        xp: 50,
        alloyChance: 1.0,
        color: '#1E3A5F',
        accent: '#60A5FA',
        spawnAfter: 11,
        weight: 0,
    },
    // 自爆母体：附近有敌人时自爆
    {
        id: 'bomber-mother',
        name: '自爆母体',
        family: 'bomber-mother',
        artId: 'bomber',
        hp: 500,
        speed: 50,
        damage: 40,
        radius: 22,
        xp: 50,
        alloyChance: 1.0,
        color: '#7F1D1D',
        accent: '#FCA5A5',
        spawnAfter: 11,
        weight: 0,
    },
    // 迅捷分裂体：极快+分裂
    {
        id: 'splitter-swift',
        name: '迅捷分裂体',
        family: 'splitter-swift',
        artId: 'splitter',
        hp: 350,
        speed: 200,
        damage: 20,
        radius: 22,
        xp: 50,
        alloyChance: 1.0,
        color: '#4C1D95',
        accent: '#C4B5FD',
        spawnAfter: 11,
        weight: 0,
    },
    // 再生巨兽：HP缓慢回复
    {
        id: 'warden-regen',
        name: '再生巨兽',
        family: 'warden-regen',
        artId: 'warden',
        hp: 700,
        speed: 40,
        damage: 28,
        radius: 34,
        xp: 50,
        alloyChance: 1.0,
        color: '#064E3B',
        accent: '#34D399',
        spawnAfter: 11,
        weight: 0,
    },
];

// ── 大 Boss（波10，每 Cycle 随机选一个）───────────────────────────
export const BOSS_SPECS: EnemySpec[] = [
    {
        id: 'void-colossus',
        name: '虚空巨像',
        family: 'void-colossus',
        artId: 'void-colossus',
        hp: 800,
        speed: 60,
        damage: 20,
        radius: 60,
        xp: 200,
        alloyChance: 1.0,
        color: '#0F0A1A',
        accent: '#22D3EE',
        spawnAfter: 50,
        weight: 0,
        bossMaterial: 'voidFragment',
    },
    {
        id: 'energy-worm',
        name: '噬能蠕虫',
        family: 'energy-worm',
        artId: 'energy-worm',
        hp: 600,
        speed: 180,
        damage: 28,
        radius: 45,
        xp: 200,
        alloyChance: 1.0,
        color: '#2D3A1A',
        accent: '#A3E635',
        spawnAfter: 50,
        weight: 0,
        bossMaterial: 'energyCore',
    },
    {
        id: 'frost-queen',
        name: '冰霜女皇',
        family: 'frost-queen',
        artId: 'frost-queen',
        hp: 750,
        speed: 80,
        damage: 24,
        radius: 52,
        xp: 200,
        alloyChance: 1.0,
        color: '#1A2A3A',
        accent: '#7DD3FC',
        spawnAfter: 50,
        weight: 0,
        bossMaterial: 'frostCore',
    },
    {
        id: 'inferno-lord',
        name: '狱炎领主',
        family: 'inferno-lord',
        artId: 'inferno-lord',
        hp: 950,
        speed: 40,
        damage: 30,
        radius: 58,
        xp: 200,
        alloyChance: 1.0,
        color: '#2A1A0A',
        accent: '#FB923C',
        spawnAfter: 50,
        weight: 0,
        bossMaterial: 'infernoCore',
    },
    {
        id: 'web-spinner',
        name: '虚空织网者',
        family: 'void-weaver',
        artId: 'web-spinner',
        hp: 700,
        speed: 75,
        damage: 22,
        radius: 50,
        xp: 200,
        alloyChance: 1.0,
        color: '#2A2A0A',
        accent: '#FACC15',
        spawnAfter: 50,
        weight: 0,
        bossMaterial: 'webSilk',
    },
];

export interface EnemyVariantDef {
    id: string;
    prefix: string;
    hp: number;
    speed: number;
    damage: number;
    radius: number;
    xp: number;
    alloy: number;
    spawn: number;
    weight: number;
}

export const ENEMY_VARIANTS: EnemyVariantDef[] = [
    { id: '', prefix: '', hp: 1, speed: 1, damage: 1, radius: 1, xp: 1, alloy: 1, spawn: 0, weight: 1 },
    { id: 'acid', prefix: '腐蚀', hp: 1.12, speed: 0.96, damage: 1.18, radius: 1, xp: 1.12, alloy: 1.2, spawn: 6, weight: 0.86 },
    { id: 'crystal', prefix: '晶化', hp: 1.38, speed: 0.88, damage: 1.08, radius: 1.05, xp: 1.24, alloy: 1.35, spawn: 10, weight: 0.78 },
    { id: 'swift', prefix: '迅捷', hp: 0.82, speed: 1.34, damage: 1.06, radius: 0.94, xp: 1.16, alloy: 1.05, spawn: 14, weight: 0.82 },
    { id: 'armored', prefix: '装甲', hp: 1.72, speed: 0.78, damage: 1.12, radius: 1.08, xp: 1.42, alloy: 1.55, spawn: 22, weight: 0.58 },
    { id: 'rage', prefix: '暴怒', hp: 1.18, speed: 1.16, damage: 1.42, radius: 1.02, xp: 1.32, alloy: 1.3, spawn: 30, weight: 0.52 },
    { id: 'shade', prefix: '幽影', hp: 0.94, speed: 1.22, damage: 1.22, radius: 0.9, xp: 1.28, alloy: 1.24, spawn: 38, weight: 0.48 },
    { id: 'arc', prefix: '电弧', hp: 1.24, speed: 1.08, damage: 1.32, radius: 1, xp: 1.44, alloy: 1.42, spawn: 48, weight: 0.42 },
    { id: 'regen', prefix: '再生', hp: 1.58, speed: 0.94, damage: 1.18, radius: 1.04, xp: 1.5, alloy: 1.48, spawn: 58, weight: 0.36 },
    { id: 'venom', prefix: '剧毒', hp: 1.3, speed: 1.06, damage: 1.58, radius: 1, xp: 1.62, alloy: 1.58, spawn: 68, weight: 0.3 },
    { id: 'prime', prefix: '原初', hp: 2.1, speed: 1.05, damage: 1.85, radius: 1.16, xp: 2.05, alloy: 2.1, spawn: 78, weight: 0.22 },
];

export function buildEnemyCatalog(): EnemySpec[] {
    const enemies: EnemySpec[] = [];
    for (const base of BASE_ENEMY_ARCHETYPES) {
        for (let variantIndex = 0; variantIndex < ENEMY_VARIANTS.length; variantIndex++) {
            const variant = ENEMY_VARIANTS[variantIndex];
            const suffix = variant.id ? `-${variant.id}` : '';
            enemies.push({
                ...base,
                id: `${base.id}${suffix}`,
                name: `${variant.prefix}${base.name}`,
                variantId: variant.id || 'base',
                variantIndex,
                hp: Math.round(base.hp * variant.hp),
                speed: Math.round(base.speed * variant.speed),
                damage: Math.max(2, Math.round(base.damage * variant.damage)),
                radius: Math.max(9, Math.round(base.radius * variant.radius)),
                xp: Math.max(1, Math.round(base.xp * variant.xp)),
                alloyChance: Math.min(0.85, Number((base.alloyChance * variant.alloy).toFixed(3))),
                spawnAfter: base.spawnAfter + variant.spawn,
                weight: Number(Math.max(0.12, base.weight * variant.weight).toFixed(2)),
            });
        }
    }
    return enemies;
}

export const ENEMY_SPECS: EnemySpec[] = buildEnemyCatalog();
export const BOSS_FAMILIES = BOSS_SPECS.map(s => s.family);
export const TOTAL_ENEMY_TYPES = ENEMY_SPECS.length + BOSS_SPECS.length;
